import os
import re

TARGET_DIR = '/Volumes/PRO-G40/FANZONE/lib'

def fix_file(filepath):
    with open(filepath, 'r') as f:
        original = f.read()
    
    content = original

    # 1. If the file is a part file, it cannot have imports. 
    # Let's remove the specific imports we added if 'part of' is in the file.
    if 'part of ' in content:
        content = re.sub(r'import\s+[\'"].*?fz_glass_loader\.dart[\'"];\n', '', content)
        content = re.sub(r'import\s+[\'"].*?fz_shimmer\.dart[\'"];\n', '', content)
    
    # 2. Fix fz_glass_loader.dart self import
    if filepath.endswith('fz_glass_loader.dart'):
        content = re.sub(r'import\s+[\'"].*?fz_glass_loader\.dart[\'"];\n', '', content)
        content = content.replace('.withOpacity(', '.withValues(alpha: ')

    # 3. Fix unnecessary const generated by replacing 'Center(child: CircularProgressIndicator())'
    # with 'const FzGlassLoader()' inside an already const array or const context.
    # The analyze step points them out. We'll simply let 'dart format' and standard compilation handle the rest,
    # except 'const const' which breaks compilation.
    content = content.replace('const const', 'const')
    
    # Let's just blindly remove the const on FzGlassLoader/ScoresPageSkeleton if it follows a 'const' keyword earlier?
    # Actually, analyze said "Unnecessary 'const' keyword". It's a warning/info, NOT an error!
    # "error: The part-of directive must be the only directive in a part" is the ONLY actual error breaking compilation.

    # 4. In `predict_slips_view.dart`, etc., the imports were added. The logic for #1 will fix it.

    if content != original:
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"Fixed {filepath}")

if __name__ == '__main__':
    for root, dirs, files in os.walk(TARGET_DIR):
        for file in files:
            if file.endswith('.dart'):
                filepath = os.path.join(root, file)
                fix_file(filepath)
    print("Cleanup done.")
