/// Pre-match AI prediction analysis generated by Gemini.
/// Maps to `public.match_ai_analysis` (migration 010).
class MatchAiAnalysis {
  final String id;
  final String matchId;
  final String analysisType;
  final String? predictedOutcome;
  final double? confidenceScore;
  final int? predictedScoreHome;
  final int? predictedScoreAway;
  final String? homeFormSummary;
  final String? awayFormSummary;
  final String? h2hSummary;
  final List<AiKeyFactor> keyFactors;
  final String? analysisNarrative;
  final String modelVersion;
  final DateTime? generatedAt;
  final DateTime? expiresAt;

  const MatchAiAnalysis({
    required this.id,
    required this.matchId,
    this.analysisType = 'pre_match',
    this.predictedOutcome,
    this.confidenceScore,
    this.predictedScoreHome,
    this.predictedScoreAway,
    this.homeFormSummary,
    this.awayFormSummary,
    this.h2hSummary,
    this.keyFactors = const [],
    this.analysisNarrative,
    this.modelVersion = 'gemini-2.0-flash',
    this.generatedAt,
    this.expiresAt,
  });

  factory MatchAiAnalysis.fromJson(Map<String, dynamic> json) {
    final rawFactors = json['key_factors'];
    final factors = <AiKeyFactor>[];
    if (rawFactors is List) {
      for (final f in rawFactors) {
        if (f is Map<String, dynamic>) {
          factors.add(AiKeyFactor.fromJson(f));
        }
      }
    }

    return MatchAiAnalysis(
      id: json['id'] as String,
      matchId: json['match_id'] as String,
      analysisType: json['analysis_type'] as String? ?? 'pre_match',
      predictedOutcome: json['predicted_outcome'] as String?,
      confidenceScore: (json['confidence_score'] as num?)?.toDouble(),
      predictedScoreHome: json['predicted_score_home'] as int?,
      predictedScoreAway: json['predicted_score_away'] as int?,
      homeFormSummary: json['home_form_summary'] as String?,
      awayFormSummary: json['away_form_summary'] as String?,
      h2hSummary: json['h2h_summary'] as String?,
      keyFactors: factors,
      analysisNarrative: json['analysis_narrative'] as String?,
      modelVersion: json['model_version'] as String? ?? 'gemini-2.0-flash',
      generatedAt: json['generated_at'] != null
          ? DateTime.tryParse(json['generated_at'] as String)
          : null,
      expiresAt: json['expires_at'] != null
          ? DateTime.tryParse(json['expires_at'] as String)
          : null,
    );
  }

  /// Whether the analysis is still valid (before match kickoff).
  bool get isValid => expiresAt == null || expiresAt!.isAfter(DateTime.now());

  /// Human-readable confidence percentage.
  String get confidenceLabel {
    if (confidenceScore == null) return '--';
    return '${(confidenceScore! * 100).toStringAsFixed(0)}%';
  }

  /// Predicted outcome as readable text.
  String get outcomeLabel {
    switch (predictedOutcome) {
      case '1':
        return 'Home Win';
      case 'X':
        return 'Draw';
      case '2':
        return 'Away Win';
      default:
        return predictedOutcome ?? 'No prediction';
    }
  }

  /// Predicted score display (e.g. "2-1").
  String? get predictedScoreDisplay {
    if (predictedScoreHome == null || predictedScoreAway == null) return null;
    return '$predictedScoreHome - $predictedScoreAway';
  }
}

/// A single key factor that influences the AI prediction.
class AiKeyFactor {
  final String factor;
  final String impact; // 'positive', 'negative', 'neutral'
  final String description;

  const AiKeyFactor({
    required this.factor,
    required this.impact,
    required this.description,
  });

  factory AiKeyFactor.fromJson(Map<String, dynamic> json) {
    return AiKeyFactor(
      factor: json['factor'] as String? ?? '',
      impact: json['impact'] as String? ?? 'neutral',
      description: json['description'] as String? ?? '',
    );
  }

  bool get isPositive => impact == 'positive';
  bool get isNegative => impact == 'negative';
}
