import 'package:freezed_annotation/freezed_annotation.dart';

part 'team_news_model.freezed.dart';
part 'team_news_model.g.dart';

/// AI-curated team news article.
///
/// Generated by the Gemini grounded research workflow, stored
/// with source traceability, and published via admin review.
@freezed
class TeamNewsModel with _$TeamNewsModel {
  const factory TeamNewsModel({
    required String id,
    @JsonKey(name: 'team_id') required String teamId,
    required String title,
    String? summary,
    String? content,
    @Default('general') String category,
    @JsonKey(name: 'source_url') String? sourceUrl,
    @JsonKey(name: 'source_name') String? sourceName,
    @JsonKey(name: 'image_url') String? imageUrl,
    @JsonKey(name: 'published_at') DateTime? publishedAt,
    required String status,
    @JsonKey(name: 'is_ai_curated') @Default(true) bool isAiCurated,
    @Default({}) Map<String, dynamic> metadata,
    @JsonKey(name: 'created_at') DateTime? createdAt,
  }) = _TeamNewsModel;

  factory TeamNewsModel.fromJson(Map<String, dynamic> json) =>
      _$TeamNewsModelFromJson(json);
}

/// News category constants for type-safe filtering.
abstract final class TeamNewsCategory {
  static const breakingNews = 'breaking_news';
  static const transfers = 'transfers';
  static const matchUpdates = 'match_updates';
  static const clubAnnouncements = 'club_announcements';
  static const fanCommunityNews = 'fan_community_news';
  static const general = 'general';

  static const all = [
    breakingNews,
    transfers,
    matchUpdates,
    clubAnnouncements,
    fanCommunityNews,
    general,
  ];

  static String label(String category) {
    switch (category) {
      case breakingNews:
        return 'Breaking';
      case transfers:
        return 'Transfers';
      case matchUpdates:
        return 'Match Updates';
      case clubAnnouncements:
        return 'Club News';
      case fanCommunityNews:
        return 'Fan News';
      case general:
      default:
        return 'General';
    }
  }
}
