import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';

enum AppIconName {
  home,
  bars,
  play,
  orders,
  wallet,
  profile,
  search,
  filter,
  cart,
  fet,
  pool,
  game,
  team,
  invite,
  payment,
  momo,
  revolut,
  timer,
  lock,
  unlock,
  eligible,
  warning,
  trophy,
  star,
  football,
  music,
  trivia,
  bingo,
  location,
  clock,
  calendar,
  bell,
  settings,
  check,
  close,
  plus,
  minus,
  share,
  scan,
  leaderboard,
  userId,
  live,
  orderNeeded,
  settled,
  pending,
}

abstract final class AppIcons {
  static const _base = 'assets/icons';

  static String? svg(AppIconName name) => switch (name) {
    AppIconName.home => '$_base/home.svg',
    AppIconName.bars => '$_base/bars.svg',
    AppIconName.play => '$_base/play.svg',
    AppIconName.orders => '$_base/orders.svg',
    AppIconName.wallet => '$_base/wallet.svg',
    AppIconName.fet => '$_base/fet.svg',
    AppIconName.pool => '$_base/pool.svg',
    AppIconName.game => '$_base/game.svg',
    AppIconName.team => '$_base/team.svg',
    AppIconName.invite => '$_base/invite.svg',
    AppIconName.payment => '$_base/payment.svg',
    AppIconName.momo => '$_base/momo.svg',
    AppIconName.revolut => '$_base/revolut.svg',
    AppIconName.timer => '$_base/timer.svg',
    AppIconName.trophy => '$_base/trophy.svg',
    AppIconName.location => '$_base/location.svg',
    AppIconName.userId => '$_base/user-id.svg',
    AppIconName.live => '$_base/live.svg',
    _ => null,
  };

  static IconData data(AppIconName name) => switch (name) {
    AppIconName.home => LucideIcons.home,
    AppIconName.bars => LucideIcons.store,
    AppIconName.play => LucideIcons.swords,
    AppIconName.orders => LucideIcons.receipt,
    AppIconName.wallet => LucideIcons.wallet,
    AppIconName.profile => LucideIcons.user,
    AppIconName.search => LucideIcons.search,
    AppIconName.filter => LucideIcons.slidersHorizontal,
    AppIconName.cart => LucideIcons.shoppingCart,
    AppIconName.fet => LucideIcons.zap,
    AppIconName.pool => LucideIcons.trophy,
    AppIconName.game => LucideIcons.gamepad2,
    AppIconName.team => LucideIcons.users,
    AppIconName.invite => LucideIcons.userPlus,
    AppIconName.payment => LucideIcons.creditCard,
    AppIconName.momo => LucideIcons.smartphone,
    AppIconName.revolut => LucideIcons.creditCard,
    AppIconName.timer => LucideIcons.timer,
    AppIconName.lock => LucideIcons.lock,
    AppIconName.unlock => LucideIcons.unlock,
    AppIconName.eligible => LucideIcons.badgeCheck,
    AppIconName.warning => LucideIcons.alertTriangle,
    AppIconName.trophy => LucideIcons.trophy,
    AppIconName.star => LucideIcons.star,
    AppIconName.football => LucideIcons.circleDot,
    AppIconName.music => LucideIcons.music,
    AppIconName.trivia => LucideIcons.helpCircle,
    AppIconName.bingo => LucideIcons.grid,
    AppIconName.location => LucideIcons.mapPin,
    AppIconName.clock => LucideIcons.clock,
    AppIconName.calendar => LucideIcons.calendar,
    AppIconName.bell => LucideIcons.bell,
    AppIconName.settings => LucideIcons.settings,
    AppIconName.check => LucideIcons.check,
    AppIconName.close => LucideIcons.x,
    AppIconName.plus => LucideIcons.plus,
    AppIconName.minus => LucideIcons.minus,
    AppIconName.share => LucideIcons.share2,
    AppIconName.scan => LucideIcons.scanLine,
    AppIconName.leaderboard => LucideIcons.listOrdered,
    AppIconName.userId => LucideIcons.badge,
    AppIconName.live => LucideIcons.activity,
    AppIconName.orderNeeded => LucideIcons.utensils,
    AppIconName.settled => LucideIcons.checkCircle2,
    AppIconName.pending => LucideIcons.hourglass,
  };
}
