// FANZONE Admin — Route Constants
export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  USERS: '/users',
  USER_DETAIL: '/users/:id',
  COMPETITIONS: '/competitions',
  COMPETITION_DETAIL: '/competitions/:id',
  FIXTURES: '/fixtures',
  FIXTURE_DETAIL: '/fixtures/:id',
  PREDICTIONS: '/predictions',
  CHALLENGES: '/challenges',
  CHALLENGE_DETAIL: '/challenges/:id',
  EVENTS: '/events',
  EVENT_DETAIL: '/events/:id',
  TOKENS: '/tokens',
  WALLETS: '/wallets',
  WALLET_DETAIL: '/wallets/:userId',
  PARTNERS: '/partners',
  PARTNER_DETAIL: '/partners/:id',
  REWARDS: '/rewards',
  REWARD_DETAIL: '/rewards/:id',
  REDEMPTIONS: '/redemptions',
  CONTENT: '/content',
  MODERATION: '/moderation',
  ANALYTICS: '/analytics',
  ACCOUNT_DELETIONS: '/account-deletions',
  SETTINGS: '/settings',
  ADMIN_ACCESS: '/admin-access',
  AUDIT_LOGS: '/audit-logs',
  NOTIFICATIONS: '/notifications',
} as const;
