#!/usr/bin/env python3
"""Generate comprehensive first-division football team database as SQL + JSON."""
import json, re, unicodedata

def slugify(name, cc):
    s = unicodedata.normalize('NFD', name.lower())
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    s = re.sub(r'[^a-z0-9\s-]', '', s).strip()
    s = re.sub(r'\s+', '-', s)
    s = re.sub(r'-+', '-', s)
    return f"{cc.lower()}-{s}"

def esc(s): return s.replace("'", "''")

# Format: (country, cc, league): [(name, short, [aliases])]
L = {}
def add(country, cc, league, teams):
    L[(country, cc, league)] = teams

# ═══════ EUROPE ═══════
add("England","GB","Premier League",[("Arsenal","ARS",["Gunners"]),("Aston Villa","AVL",["Villa"]),("AFC Bournemouth","BOU",["Cherries"]),("Brentford","BRE",["Bees"]),("Brighton & Hove Albion","BHA",["Brighton","Seagulls"]),("Chelsea","CHE",["Blues"]),("Crystal Palace","CRY",["Eagles"]),("Everton","EVE",["Toffees"]),("Fulham","FUL",[]),("Ipswich Town","IPS",["Tractor Boys"]),("Leicester City","LEI",["Foxes"]),("Liverpool","LIV",["Reds"]),("Manchester City","MCI",["City","Citizens"]),("Manchester United","MUN",["United","Red Devils"]),("Newcastle United","NEW",["Magpies"]),("Nottingham Forest","NFO",["Forest"]),("Southampton","SOU",["Saints"]),("Tottenham Hotspur","TOT",["Spurs"]),("West Ham United","WHU",["Hammers"]),("Wolverhampton Wanderers","WOL",["Wolves"])])
add("Scotland","XS","Scottish Premiership",[("Celtic","CEL",["Bhoys"]),("Rangers","RAN",["Gers"]),("Aberdeen","ABD",["Dons"]),("Hibernian","HIB",["Hibs"]),("Heart of Midlothian","HEA",["Hearts"]),("Dundee United","DUU",[]),("Dundee","DUN",[]),("Kilmarnock","KIL",[]),("Motherwell","MOT",[]),("Ross County","ROS",[]),("St Mirren","STM",[]),("St Johnstone","STJ",[])])
add("Wales","XW","Cymru Premier",[("The New Saints","TNS",[]),("Connah's Quay Nomads","CQN",[]),("Bala Town","BAL",[]),("Caernarfon Town","CAE",[]),("Penybont","PEN",[]),("Haverfordwest County","HAV",[]),("Newtown","NWT",[]),("Flint Town United","FLI",[]),("Briton Ferry Llansawel","BFL",[]),("Aberystwyth Town","ABE",[]),("Barry Town United","BTU",[]),("Cardiff Metropolitan","CMU",[])])
add("Northern Ireland","XI","NIFL Premiership",[("Linfield","LIN",[]),("Glentoran","GLE",[]),("Cliftonville","CLI",[]),("Crusaders","CRU",[]),("Larne","LAR",[]),("Coleraine","COL",[]),("Ballymena United","BAU",[]),("Glenavon","GLV",[]),("Carrick Rangers","CAR",[]),("Dungannon Swifts","DGS",[]),("Portadown","POR",[]),("Newry City","NRY",[])])
add("Spain","ES","La Liga",[("Real Madrid","RMA",["Los Blancos"]),("Barcelona","BAR",["Barca"]),("Atletico Madrid","ATM",["Atleti"]),("Athletic Bilbao","ATH",[]),("Real Sociedad","RSO",[]),("Real Betis","BET",[]),("Villarreal","VIL",[]),("Sevilla","SEV",[]),("Osasuna","OSA",[]),("Celta Vigo","CEL",[]),("Mallorca","MLL",[]),("Girona","GIR",[]),("Rayo Vallecano","RAY",[]),("Getafe","GET",[]),("Alaves","ALA",[]),("Valencia","VAL",[]),("Espanyol","ESP",[]),("Leganes","LEG",[]),("Las Palmas","LPA",[]),("Real Valladolid","VLL",[])])
add("Germany","DE","Bundesliga",[("Bayern Munich","FCB",["Bayern"]),("Borussia Dortmund","BVB",["Dortmund"]),("Bayer Leverkusen","LEV",[]),("RB Leipzig","RBL",[]),("VfB Stuttgart","STU",[]),("Eintracht Frankfurt","SGE",[]),("SC Freiburg","SCF",[]),("Borussia Monchengladbach","BMG",["Gladbach"]),("Union Berlin","FCU",[]),("Werder Bremen","SVW",[]),("VfL Wolfsburg","WOB",[]),("TSG Hoffenheim","TSG",[]),("Mainz 05","M05",[]),("FC Augsburg","FCA",[]),("Heidenheim","FCH",[]),("Holstein Kiel","KIE",[]),("FC St. Pauli","STP",[]),("VfL Bochum","BOC",[])])
add("France","FR","Ligue 1",[("Paris Saint-Germain","PSG",[]),("Olympique de Marseille","OM",["Marseille"]),("AS Monaco","MON",[]),("Olympique Lyonnais","OL",["Lyon"]),("LOSC Lille","LIL",[]),("OGC Nice","NIC",[]),("RC Lens","RCL",[]),("Stade Rennais","REN",["Rennes"]),("Stade Brestois","BRS",["Brest"]),("RC Strasbourg","RCS",[]),("Toulouse FC","TFC",[]),("Montpellier HSC","MTP",[]),("FC Nantes","NAN",[]),("AJ Auxerre","AUX",[]),("AS Saint-Etienne","STE",[]),("Angers SCO","ANG",[]),("Stade de Reims","REI",[]),("Le Havre AC","HAV",[])])
add("Italy","IT","Serie A",[("Inter Milan","INT",["Nerazzurri"]),("AC Milan","MIL",["Rossoneri"]),("Juventus","JUV",["Bianconeri"]),("SSC Napoli","NAP",[]),("AS Roma","ROM",[]),("SS Lazio","LAZ",[]),("Atalanta","ATA",[]),("ACF Fiorentina","FIO",["Viola"]),("Bologna","BOL",[]),("Torino","TOR",[]),("Udinese","UDI",[]),("Cagliari","CAG",[]),("Empoli","EMP",[]),("Hellas Verona","VER",[]),("US Lecce","LEC",[]),("Genoa","GEN",[]),("Parma","PAR",[]),("Como 1907","COM",[]),("Monza","MON",[]),("Venezia","VEN",[])])
add("Portugal","PT","Primeira Liga",[("SL Benfica","BEN",["Benfica"]),("FC Porto","POR",["Porto"]),("Sporting CP","SCP",["Sporting"]),("SC Braga","BRA",[]),("Vitoria SC","VSC",[]),("Gil Vicente","GIL",[]),("Casa Pia AC","CPA",[]),("CD Santa Clara","STC",[]),("Famalicao","FAM",[]),("Moreirense","MOR",[]),("Rio Ave","RIO",[]),("Arouca","ARO",[]),("Nacional","NAC",[]),("Estoril Praia","EST",[]),("Boavista","BOA",[]),("Estrela da Amadora","EAM",[]),("AVS Futebol SAD","AVS",[]),("Farense","FAR",[])])
add("Netherlands","NL","Eredivisie",[("Ajax","AJA",[]),("PSV Eindhoven","PSV",[]),("Feyenoord","FEY",[]),("AZ Alkmaar","AZ",[]),("FC Twente","TWE",[]),("FC Utrecht","UTR",[]),("Go Ahead Eagles","GAE",[]),("NEC Nijmegen","NEC",[]),("sc Heerenveen","HEE",[]),("Fortuna Sittard","FOR",[]),("Sparta Rotterdam","SPA",[]),("Heracles Almelo","HER",[]),("PEC Zwolle","PEC",[]),("Willem II","WIL",[]),("NAC Breda","NAB",[]),("RKC Waalwijk","RKC",[]),("Almere City FC","ALM",[]),("FC Groningen","GRO",[])])
add("Belgium","BE","Pro League",[("Club Brugge","CLB",[]),("RSC Anderlecht","AND",[]),("KAA Gent","GEN",[]),("Union Saint-Gilloise","USG",[]),("Royal Antwerp","ANT",[]),("Cercle Brugge","CEB",[]),("KRC Genk","GNK",[]),("Standard Liege","STA",[]),("OH Leuven","OHL",[]),("KV Mechelen","KVM",[]),("Sint-Truidense VV","STT",[]),("Charleroi","CHA",[]),("KV Kortrijk","KVK",[]),("Westerlo","WES",[]),("FCV Dender","DEN",[]),("Beerschot VA","BEE",[])])
add("Turkey","TR","Super Lig",[("Galatasaray","GAL",[]),("Fenerbahce","FEN",[]),("Besiktas","BJK",[]),("Trabzonspor","TRA",[]),("Istanbul Basaksehir","BAS",[]),("Kasimpasa","KAS",[]),("Antalyaspor","ANT",[]),("Sivasspor","SIV",[]),("Konyaspor","KON",[]),("Alanyaspor","ALA",[]),("Hatayspor","HAT",[]),("Caykur Rizespor","RIZ",[]),("Adana Demirspor","ADS",[]),("Kayserispor","KAY",[]),("Samsunspor","SAM",[]),("Gaziantep FK","GAZ",[]),("Bodrum FK","BOD",[]),("Pendikspor","PND",[])])
add("Greece","GR","Super League",[("Olympiacos","OLY",[]),("Panathinaikos","PAO",[]),("AEK Athens","AEK",[]),("PAOK","PAK",[]),("Aris Thessaloniki","ARI",[]),("Asteras Tripolis","AST",[]),("Atromitos","ATR",[]),("OFI Crete","OFI",[]),("Volos NFC","VOL",[]),("Panserraikos","PAN",[]),("Lamia","LAM",[]),("Levadiakos","LEV",[]),("Kallithea","KAL",[]),("Panetolikos","PNT",[])])
add("Austria","AT","Austrian Bundesliga",[("Red Bull Salzburg","RBS",[]),("SK Sturm Graz","STU",[]),("SK Rapid Wien","RAP",[]),("FK Austria Wien","AUS",[]),("LASK","LAS",[]),("Wolfsberger AC","WAC",[]),("TSV Hartberg","HAR",[]),("SCR Altach","ALT",[]),("WSG Tirol","WSG",[]),("Blau-Weiss Linz","BWL",[]),("GAK 1902","GAK",[])])
add("Switzerland","CH","Super League",[("BSC Young Boys","YB",[]),("FC Basel","BAS",[]),("FC Zurich","FCZ",[]),("FC Lugano","LUG",[]),("Servette FC","SFC",[]),("FC St. Gallen","STG",[]),("FC Luzern","LUZ",[]),("FC Sion","SIO",[]),("Grasshoppers","GCZ",[]),("FC Lausanne-Sport","LAU",[]),("FC Winterthur","WIN",[]),("Yverdon Sport FC","YVE",[])])
add("Sweden","SE","Allsvenskan",[("Malmo FF","MFF",[]),("AIK","AIK",[]),("Djurgardens IF","DIF",[]),("Hammarby IF","HAM",[]),("IF Elfsborg","ELF",[]),("IFK Goteborg","IFG",[]),("IFK Norrkoping","NOR",[]),("BK Hacken","HAC",[]),("Kalmar FF","KAL",[]),("IF Brommapojkarna","BRO",[]),("Varnamo","VAR",[]),("Mjallby AIF","MJA",[]),("Halmstads BK","HBK",[]),("GAIS","GAI",[]),("Sirius","SIR",[]),("Degerfors IF","DEG",[])])
add("Norway","NO","Eliteserien",[("Bodo/Glimt","GLI",[]),("Molde FK","MOL",[]),("Rosenborg","RBK",[]),("SK Brann","BRA",[]),("Viking FK","VIK",[]),("Valerenga","VIF",[]),("Lillestrom","LSK",[]),("Stromsgodset","SIF",[]),("Tromso IL","TIL",[]),("Sarpsborg 08","SAR",[]),("Haugesund","FKH",[]),("Odd","ODD",[]),("HamKam","HKM",[]),("Sandefjord","SAN",[]),("Stabaek","STB",[]),("Kristiansund BK","KBK",[])])
add("Denmark","DK","Superliga",[("FC Copenhagen","FCK",[]),("FC Midtjylland","FCM",[]),("Brondby IF","BIF",[]),("FC Nordsjaelland","FCN",[]),("AGF Aarhus","AGF",[]),("Randers FC","RFC",[]),("Silkeborg IF","SIF",[]),("Viborg FF","VFF",[]),("OB","OB",[]),("Lyngby BK","LBK",[]),("AaB","AAB",[]),("SonderjyskE","SOE",[])])
add("Poland","PL","Ekstraklasa",[("Legia Warsaw","LEG",[]),("Lech Poznan","LPO",[]),("Rakow Czestochowa","RAK",[]),("Jagiellonia Bialystok","JAG",[]),("Pogon Szczecin","POG",[]),("Slask Wroclaw","SLA",[]),("Piast Gliwice","PIA",[]),("Cracovia","CRA",[]),("Gornik Zabrze","GOR",[]),("Korona Kielce","KOR",[]),("Widzew Lodz","WID",[]),("Stal Mielec","STA",[]),("Puszcza Niepolomice","PUS",[]),("Motor Lublin","MOT",[]),("GKS Katowice","GKS",[]),("Radomiak Radom","RAD",[]),("Warta Poznan","WAR",[]),("Zaglebie Lubin","ZAG",[])])
add("Czech Republic","CZ","Czech First League",[("Sparta Prague","SPA",[]),("Slavia Prague","SLA",[]),("Viktoria Plzen","PLZ",[]),("Banik Ostrava","BAN",[]),("Sigma Olomouc","SIG",[]),("FK Jablonec","JAB",[]),("FK Teplice","TEP",[]),("Bohemians 1905","BOH",[]),("Slovacko","SLO",[]),("FK Mlada Boleslav","MBO",[]),("Liberec","LIB",[]),("Hradec Kralove","HRA",[]),("Dukla Prague","DUK",[]),("Karvina","KAR",[]),("Pardubice","PAR",[]),("Ceske Budejovice","CEB",[])])
add("Romania","RO","SuperLiga",[("FCSB","FCS",["Steaua"]),("CFR Cluj","CFR",[]),("Universitatea Craiova","UCR",[]),("Rapid Bucuresti","RAP",[]),("Universitatea Cluj","UCL",[]),("Sepsi OSK","SEP",[]),("Farul Constanta","FAR",[]),("FC Botosani","BOT",[]),("UTA Arad","UTA",[]),("Dinamo Bucuresti","DIN",[]),("Otelul Galati","OTE",[]),("Petrolul Ploiesti","PET",[]),("Hermannstadt","HER",[]),("Poli Iasi","POL",[]),("Gloria Buzau","GLO",[])])
add("Hungary","HU","NB I",[("Ferencvaros","FTC",[]),("MOL Fehervar","FEH",[]),("Puskas Akademia","PUS",[]),("Paksi FC","PAK",[]),("Diosgyor VTK","DVT",[]),("Kecskemet","KEC",[]),("Debrecen","DEB",[]),("Ujpest","UJP",[]),("Zalaegerszegi TE","ZTE",[]),("Budapest Honved","HON",[]),("Vasas","VAS",[])])
add("Croatia","HR","HNL",[("Dinamo Zagreb","DZG",[]),("Hajduk Split","HAJ",[]),("Rijeka","RIJ",[]),("Osijek","OSI",[]),("Lokomotiva Zagreb","LOK",[]),("NK Istra 1961","IST",[]),("Slaven Belupo","SLB",[]),("Gorica","GOR",[]),("Varazdin","VAR",[]),("Sibenik","SIB",[])])
add("Serbia","RS","SuperLiga",[("Red Star Belgrade","CZV",["Crvena Zvezda"]),("Partizan Belgrade","PAR",[]),("Vojvodina","VOJ",[]),("FK Cukaricki","CUK",[]),("TSC Backa Topola","TSC",[]),("Radnicki Nis","RAD",[]),("FK Napredak","NAP",[]),("FK Novi Pazar","NPA",[]),("FK Spartak Subotica","SPR",[]),("FK IMT Novi Beograd","IMT",[]),("FK Tekstilac","TEK",[]),("FK Kolubara","KOL",[]),("FK Mladost Lucani","MLA",[])])
add("Ukraine","UA","Ukrainian Premier League",[("Shakhtar Donetsk","SHA",[]),("Dynamo Kyiv","DYN",[]),("Dnipro-1","DN1",[]),("Zorya Luhansk","ZOR",[]),("Vorskla Poltava","VOR",[]),("Kolos Kovalivka","KOL",[]),("Oleksandriya","OLE",[]),("Chornomorets Odesa","CHO",[]),("Kryvbas","KRY",[]),("Mynai","MYN",[]),("LNZ Cherkasy","LNZ",[]),("Metalist 1925","MET",[]),("Veres Rivne","VER",[]),("Obolon Kyiv","OBO",[]),("Polissya Zhytomyr","POL",[])])
add("Bulgaria","BG","First Professional Football League",[("Ludogorets Razgrad","LUD",[]),("CSKA Sofia","CSK",[]),("Levski Sofia","LEV",[]),("Lokomotiv Plovdiv","LPL",[]),("Botev Plovdiv","BOT",[]),("Cherno More Varna","CHM",[]),("Beroe","BER",[]),("Arda Kardzhali","ARD",[]),("CSKA 1948 Sofia","C48",[]),("Slavia Sofia","SLS",[]),("Hebar Pazardzhik","HEB",[]),("Pirin Blagoevgrad","PIR",[]),("Krumovgrad","KRU",[])])
add("Slovakia","SK","Fortuna Liga",[("Slovan Bratislava","SLB",[]),("Spartak Trnava","STR",[]),("DAC Dunajska Streda","DAC",[]),("MFK Ruzomberok","RUZ",[]),("FK Zilina","ZIL",[]),("Trencin","TRE",[]),("Dukla B. Bystrica","DUK",[]),("Pohronie","POH",[]),("Skalica","SKA",[]),("Komarno","KOM",[])])
add("Slovenia","SI","PrvaLiga",[("NK Maribor","MAR",[]),("NK Olimpija Ljubljana","OLI",[]),("NK Celje","CEL",[]),("NK Domzale","DOM",[]),("NK Mura","MUR",[]),("ND Gorica","GOR",[]),("NK Bravo","BRA",[]),("NK Radomlje","RAD",[]),("NK Koper","KOP",[]),("NK Nafta","NAF",[])])
add("Cyprus","CY","Cypriot First Division",[("APOEL Nicosia","APO",[]),("Anorthosis Famagusta","ANO",[]),("Apollon Limassol","APL",[]),("AEL Limassol","AEL",[]),("Omonia Nicosia","OMO",[]),("AEK Larnaca","AEK",[]),("Nea Salamis","NEA",[]),("Pafos FC","PAF",[]),("Aris Limassol","ARI",[]),("Ethnikos Achnas","ETH",[]),("Karmiotissa","KAR",[])])
add("Malta","MT","Maltese Premier League",[("Valletta","VAL",[]),("Hamrun Spartans","HRS",[]),("Hibernians","HIB",[]),("Floriana","FLO",[]),("Birkirkara","BIR",[]),("Sliema Wanderers","SLI",[]),("Balzan","BAL",[]),("Santa Lucia","SLU",[]),("Gzira United","GZU",[]),("Mosta","MOS",[]),("Naxxar Lions","NAX",[]),("Gudja United","GUD",[]),("Sirens","SIR",[]),("Marsaxlokk","MAR",[])])
add("Ireland","IE","League of Ireland Premier Division",[("Shamrock Rovers","SHA",[]),("Shelbourne","SHE",[]),("Dundalk","DUN",[]),("Bohemian FC","BOH",[]),("Derry City","DER",[]),("St Patrick's Athletic","SPA",[]),("Sligo Rovers","SLI",[]),("Drogheda United","DRO",[]),("Galway United","GAL",[]),("Waterford","WAT",[])])
add("Iceland","IS","Urvalsdeild",[("Valur","VAL",[]),("Breidablik","BRE",[]),("Vikingur Reykjavik","VIK",[]),("FH Hafnarfjordur","FH",[]),("KR Reykjavik","KR",[]),("Stjarnan","STJ",[]),("IA Akranes","IA",[]),("Fylkir","FYL",[]),("Keflavik","KEF",[]),("Fram Reykjavik","FRA",[])])
add("Finland","FI","Veikkausliiga",[("HJK Helsinki","HJK",[]),("KuPS","KUP",[]),("Inter Turku","ITU",[]),("SJK Seinajoki","SJK",[]),("IFK Mariehamn","IFK",[]),("FC Haka","HAK",[]),("Ilves","ILV",[]),("FC Lahti","LAH",[]),("AC Oulu","ACO",[]),("VPS Vaasa","VPS",[])])
add("Albania","AL","Kategoria Superiore",[("KF Tirana","TIR",[]),("FK Partizani","PAR",[]),("KF Vllaznia","VLL",[]),("KF Laci","LAC",[]),("KF Teuta","TEU",[]),("FK Kukesi","KUK",[]),("KS Egnatia","EGN",[]),("KF Bylis","BYL",[]),("KS Kastrioti","KAS",[]),("KF Elbasani","ELB",[])])
add("Bosnia and Herzegovina","BA","Premier League BiH",[("FK Sarajevo","SAR",[]),("FK Zeljeznicar","ZEL",[]),("FK Borac Banja Luka","BOR",[]),("NK Zrinjski Mostar","ZRI",[]),("FK Velez Mostar","VEL",[]),("NK Siroki Brijeg","SIR",[]),("FK Tuzla City","TUZ",[]),("FK Sloboda Tuzla","SLO",[])])
add("North Macedonia","MK","Prva Liga",[("FK Vardar","VAR",[]),("FK Shkupi","SKP",[]),("FK Rabotnicki","RAB",[]),("FK Pelister","PEL",[]),("FK Shkendija","SKE",[]),("FK Akademija Pandev","AKP",[]),("FK Bregalnica Stip","BRE",[]),("FK Struga","STR",[])])
add("Montenegro","ME","Montenegrin First League",[("FK Buducnost Podgorica","BUD",[]),("FK Sutjeska Niksic","SUT",[]),("FK Decic Tuzi","DEC",[]),("FK Iskra","ISK",[]),("FK Rudar Pljevlja","RUD",[]),("FK Podgorica","POD",[]),("FK Mornar Bar","MOR",[]),("FK Petrovac","PET",[])])
add("Kosovo","XK","Football Superleague of Kosovo",[("FC Ballkani","BLK",[]),("KF Drita","DRI",[]),("FC Prishtina","PRI",[]),("KF Gjilani","GJI",[]),("FC Malisheva","MAL",[]),("KF Dukagjini","DUK",[]),("KF Feronikeli","FER",[]),("KF Llapi","LLP",[]),("KF Drenica","DRE",[])])
add("Moldova","MD","Moldovan Super Liga",[("FC Sheriff Tiraspol","SHE",[]),("FC Petrocub","PET",[]),("FC Zimbru Chisinau","ZIM",[]),("FC Milsami Orhei","MIL",[]),("FC Sfintul Gheorghe","SFG",[]),("FC Dinamo-Auto","DIN",[]),("FC Floresti","FLO",[])])
add("Georgia","GE","Erovnuli Liga",[("FC Dinamo Tbilisi","DIN",[]),("FC Torpedo Kutaisi","TOR",[]),("FC Dila Gori","DIL",[]),("FC Saburtalo","SAB",[]),("FC Dinamo Batumi","DBA",[]),("FC Samgurali","SAM",[]),("FC Gagra","GAG",[]),("FC Telavi","TEL",[])])
add("Armenia","AM","Armenian Premier League",[("FC Pyunik","PYU",[]),("FC Ararat-Armenia","ARA",[]),("FC Urartu","URA",[]),("FC Alashkert","ALA",[]),("FC Noah","NOA",[]),("FC Shirak","SHI",[]),("FC Van","VAN",[]),("FC West Armenia","WES",[])])
add("Azerbaijan","AZ","Azerbaijan Premier League",[("Qarabag FK","QAR",[]),("Neftci PFK","NEF",[]),("FK Zira","ZIR",[]),("Sabah FK","SAB",[]),("FK Sumgayit","SUM",[]),("FK Gabala","GAB",[]),("Turan Tovuz","TUR",[]),("MOiK Baku","MOI",[])])
add("Belarus","BY","Belarusian Premier League",[("BATE Borisov","BAT",[]),("Dinamo Minsk","DIN",[]),("Shakhtyor Soligorsk","SHA",[]),("FC Gomel","GOM",[]),("Neman Grodno","NEM",[]),("FC Isloch","ISL",[]),("Torpedo Minsk","TOR",[]),("Dinamo Brest","DBR",[]),("FC Vitebsk","VIT",[]),("FC Minsk","MIN",[])])
add("Kazakhstan","KZ","Kazakhstan Premier League",[("FC Astana","AST",[]),("FC Kairat","KAI",[]),("FK Tobol","TOB",[]),("FK Ordabasy","ORD",[]),("FK Aktobe","AKT",[]),("FK Shakhter Karagandy","SKK",[]),("FK Atyrau","ATY",[]),("FK Taraz","TAR",[]),("FK Zhetysu","ZHE",[])])
add("Estonia","EE","Meistriliiga",[("FC Flora Tallinn","FLO",[]),("FCI Levadia","LEV",[]),("Nomme Kalju FC","KAL",[]),("FC Paide","PAI",[]),("JK Narva Trans","NAR",[]),("JK Tammeka Tartu","TAM",[]),("Kuressaare","KUR",[])])
add("Latvia","LV","Virsliga",[("FK RFS","RFS",[]),("FK Liepaja","LIE",[]),("Riga FC","RIG",[]),("FK Metta","MET",[]),("BFC Daugavpils","DAU",[]),("FK Auda","AUD",[]),("Valmiera FC","VAL",[])])
add("Lithuania","LT","A Lyga",[("FK Zalgiris Vilnius","ZAL",[]),("FK Panevezys","PAN",[]),("FK Suduva","SUD",[]),("FK Kauno Zalgiris","KAZ",[]),("FA Siauliai","SIA",[]),("FK Banga","BAN",[]),("FK Dainava","DAI",[]),("FK Hegelmann","HEG",[])])
add("Luxembourg","LU","National Division",[("F91 Dudelange","DUD",[]),("FC Differdange 03","DIF",[]),("FC Progres Niederkorn","PRN",[]),("CS Fola Esch","FOL",[]),("Swift Hesperange","SWI",[]),("Jeunesse Esch","JEU",[]),("Racing FC Union","RFU",[]),("FC Etzella","ETZ",[])])
add("Russia","RU","Russian Premier League",[("Zenit St. Petersburg","ZEN",[]),("CSKA Moscow","CSK",[]),("Spartak Moscow","SPK",[]),("Lokomotiv Moscow","LOK",[]),("Dynamo Moscow","DYN",[]),("FC Krasnodar","KRA",[]),("Rostov","ROS",[]),("Akhmat Grozny","AKH",[]),("Rubin Kazan","RUB",[]),("FK Ural","URA",[]),("Krylya Sovetov","KRS",[]),("FK Orenburg","ORE",[]),("FK Baltika","BAL",[])])

# ═══════ AFRICA ═══════
add("Nigeria","NG","Nigeria Professional Football League",[("Enyimba","ENY",[]),("Kano Pillars","KPL",[]),("Rivers United","RIU",[]),("Plateau United","PLU",[]),("Remo Stars","REM",[]),("Shooting Stars","SSS",[]),("Bendel Insurance","BIN",[]),("Enugu Rangers","RAN",[]),("Heartland","HRT",[]),("Kwara United","KWU",[]),("Lobi Stars","LOB",[]),("Niger Tornadoes","NIG",[]),("Sunshine Stars","SUN",[]),("Bayelsa United","BAY",[]),("Sporting Lagos","SLG",[]),("Akwa United","AKU",[]),("El-Kanemi Warriors","ELK",[]),("Nasarawa United","NAS",[])])
add("Egypt","EG","Egyptian Premier League",[("Al Ahly","AHL",[]),("Zamalek","ZAM",[]),("Pyramids FC","PYR",[]),("Al Masry","MAS",[]),("Ismaily","ISM",[]),("Ceramica Cleopatra","CER",[]),("Smouha","SMO",[]),("ENPPI","ENP",[]),("Future FC","FUT",[]),("Pharco FC","PHR",[]),("Ghazl El Mahalla","GHZ",[]),("El Gouna","ELG",[]),("ZED FC","ZED",[]),("National Bank","NBE",[]),("Al Mokawloon","MOK",[]),("Eastern Company","EAS",[])])
add("South Africa","ZA","DStv Premiership",[("Mamelodi Sundowns","SUN",[]),("Kaizer Chiefs","KAI",["Amakhosi"]),("Orlando Pirates","PIR",["Buccaneers"]),("Stellenbosch FC","STL",[]),("Cape Town City","CTC",[]),("SuperSport United","SSU",[]),("AmaZulu","AMA",[]),("Richards Bay","RBA",[]),("Golden Arrows","GOA",[]),("TS Galaxy","TSG",[]),("Royal AM","RAM",[]),("Chippa United","CHI",[]),("Polokwane City","POL",[]),("Sekhukhune United","SEK",[]),("Moroka Swallows","SWA",[])])
add("Morocco","MA","Botola Pro",[("Wydad Casablanca","WAC",[]),("Raja Casablanca","RCA",[]),("FAR Rabat","FAR",[]),("RS Berkane","RSB",[]),("FUS Rabat","FUS",[]),("Moghreb Tetouan","MAT",[]),("Olympic Safi","OCS",[]),("Hassania Agadir","HUS",[]),("Difaa El Jadida","DHJ",[]),("Ittihad Tanger","ITT",[]),("Renaissance Zemamra","RCZ",[]),("MAS Fez","MAS",[])])
add("Tunisia","TN","Ligue Professionnelle 1",[("Esperance de Tunis","EST",[]),("Club Africain","CAF",[]),("Etoile du Sahel","ESS",[]),("US Monastir","USM",[]),("CS Sfaxien","CSS",[]),("CA Bizertin","CAB",[]),("Stade Tunisien","STT",[]),("US Ben Guerdane","USG",[]),("JS Kairouanaise","JSK",[]),("AS Soliman","ASS",[])])
add("Algeria","DZ","Ligue Professionnelle 1",[("CR Belouizdad","CRB",[]),("MC Alger","MCA",[]),("JS Kabylie","JSK",[]),("USM Alger","USM",[]),("ES Setif","ESS",[]),("CS Constantine","CSC",[]),("MC Oran","MCO",[]),("US Biskra","USB",[]),("JS Saoura","JSS",[]),("ASO Chlef","ASO",[]),("Paradou AC","PAC",[])])
add("Ghana","GH","Ghana Premier League",[("Hearts of Oak","HOA",[]),("Asante Kotoko","KOT",[]),("Medeama","MED",[]),("Dreams FC","DRE",[]),("Aduana Stars","ADU",[]),("Berekum Chelsea","BCH",[]),("Legon Cities","LEG",[]),("Bechem United","BEC",[]),("Karela United","KAR",[]),("King Faisal","KFB",[]),("Great Olympics","GOL",[]),("Samartex 1996","SAM",[]),("Nsoatreman","NSO",[]),("Real Tamale United","RTU",[])])
add("Kenya","KE","Kenyan Premier League",[("Gor Mahia","GOR",[]),("AFC Leopards","AFC",[]),("Tusker FC","TUS",[]),("KCB","KCB",[]),("Bandari","BAN",[]),("Kariobangi Sharks","KSH",[]),("Kakamega Homeboyz","KHB",[]),("Ulinzi Stars","ULI",[]),("Posta Rangers","POS",[]),("Sofapaka","SOF",[]),("Bidco United","BID",[]),("Kenya Police","KPO",[]),("Nairobi City Stars","NCS",[])])
add("Rwanda","RW","Rwanda Premier League",[("APR FC","APR",[]),("Rayon Sports","RAY",[]),("AS Kigali","ASK",[]),("Police FC","POL",[]),("Musanze FC","MUS",[]),("Mukura Victory Sports","MUK",[]),("Gasogi United","GAS",[]),("Bugesera FC","BUG",[]),("Gorilla FC","GOR",[]),("Etincelles FC","ETI",[]),("Marines FC","MAR",[]),("Sunrise FC","SUN",[]),("Kiyovu Sports","KIY",[])])
add("Tanzania","TZ","NBC Premier League",[("Young Africans","YAN",["Yanga"]),("Simba SC","SIM",[]),("Azam FC","AZA",[]),("Namungo FC","NAM",[]),("KMC FC","KMC",[]),("Kagera Sugar","KAG",[]),("Tanzania Prisons","TPR",[]),("Geita Gold","GEI",[]),("Dodoma FC","DOD",[]),("Mtibwa Sugar","MTI",[])])
add("Uganda","UG","Uganda Premier League",[("KCCA FC","KCC",[]),("Vipers SC","VIP",[]),("BUL FC","BUL",[]),("SC Villa","SCV",[]),("URA FC","URA",[]),("Express FC","EXP",[]),("UPDF FC","UPD",[]),("Wakiso Giants","WAK",[]),("Arua Hill SC","ARU",[]),("Onduparaka FC","OND",[])])
add("DR Congo","CD","Linafoot",[("TP Mazembe","TPM",[]),("AS Vita Club","VIT",[]),("DC Motema Pembe","DCM",[]),("FC Saint-Eloi Lupopo","SEL",[]),("AS Maniema Union","MAN",[]),("CS Don Bosco","CDB",[]),("FC Renaissance","REN",[]),("Lubumbashi Sport","LUB",[]),("Racing Club Kinshasa","RCK",[])])
add("Senegal","SN","Ligue 1 Senegalaise",[("Teungueth FC","TEU",[]),("Casa Sports","CAS",[]),("AS Pikine","ASP",[]),("Generation Foot","GFO",[]),("US Goree","USG",[]),("AS Douanes","ASD",[]),("Jaraaf","JAR",[]),("Diambars","DIA",[]),("Dakar Sacre-Coeur","DSC",[])])
add("Cote d'Ivoire","CI","Ligue 1 Ivoirienne",[("ASEC Mimosas","ASE",[]),("Africa Sports","AFR",[]),("Stade d'Abidjan","STA",[]),("Racing Club Abidjan","RCA",[]),("SOA","SOA",[]),("FC San Pedro","FSP",[]),("Sporting Gagnoa","SCG",[]),("Sol FC","SOL",[])])
add("Cameroon","CM","Elite One",[("Coton Sport","COT",[]),("Canon Yaounde","CAN",[]),("Bamboutos FC","BAM",[]),("Tonnerre Yaounde","TON",[]),("Union Douala","UND",[]),("Apejes Academy","APE",[]),("PWD Bamenda","PWD",[]),("Yong Sports Academy","YSA",[])])
add("Ethiopia","ET","Ethiopian Premier League",[("St. George SC","STG",[]),("Ethiopian Coffee","ECO",[]),("Fasil Kenema","FAS",[]),("Hawassa City","HAW",[]),("Adama City","ADA",[]),("Defense SC","DEF",[]),("Dire Dawa City","DDC",[]),("Jimma Aba Jifar","JAJ",[])])
add("Zambia","ZM","Zambia Super League",[("Zesco United","ZES",[]),("Nkana FC","NKA",[]),("Power Dynamos","POW",[]),("Green Buffaloes","GRB",[]),("Red Arrows","REA",[]),("Zanaco","ZAN",[]),("Forest Rangers","FOR",[]),("Napsa Stars","NAP",[]),("Prison Leopards","PRI",[])])
add("Zimbabwe","ZW","Zimbabwe Premier Soccer League",[("Dynamos FC","DYN",[]),("Highlanders FC","HIG",[]),("FC Platinum","FCP",[]),("Caps United","CAP",[]),("Chicken Inn","CHK",[]),("Ngezi Platinum Stars","NGE",[]),("Herentals","HER",[]),("Black Rhinos","BRH",[]),("Manica Diamonds","MAN",[])])
add("Angola","AO","Girabola",[("Petro de Luanda","PET",[]),("Primeiro de Agosto","PDA",[]),("Sagrada Esperanca","SAG",[]),("Interclube","INT",[]),("Recreativo do Libolo","LIB",[]),("Progresso do Sambizanga","PRO",[]),("Academica do Lobito","ADL",[]),("Desportivo da Huila","DHL",[])])
add("Mozambique","MZ","Mocambola",[("FC Costa do Sol","CDS",[]),("Ferroviario de Maputo","FER",[]),("UD Songo","UDS",[]),("CD Maxaquene","MAX",[]),("Liga Muculmana","LMD",[]),("Black Bulls FC","BBF",[]),("Ferroviario de Beira","FDB",[])])
add("Mali","ML","Premiere Division du Mali",[("Stade Malien","STM",[]),("Djoliba AC","DJO",[]),("AS Real Bamako","ARB",[]),("Centre Salif Keita","CSK",[]),("Onze Createurs","ONC",[]),("AS Police","ASP",[]),("COB Bamako","COB",[])])
add("Burkina Faso","BF","Premiere Division BF",[("ASFA Yennenga","ASY",[]),("Etoile Filante","EFO",[]),("Rail Club du Kadiogo","RCK",[]),("Rahimo FC","RAH",[]),("Salitas FC","SAL",[]),("Santos FC Ouagadougou","SAN",[])])
add("Ivory Coast","CI2","Ligue 1",[]) # skip duplicate

# ═══════ AMERICAS ═══════
add("United States","US","Major League Soccer",[("Inter Miami CF","MIA",[]),("LAFC","LAF",[]),("LA Galaxy","LAG",[]),("Atlanta United","ATL",[]),("Columbus Crew","CLB",[]),("FC Cincinnati","CIN",[]),("New York Red Bulls","RBN",[]),("New York City FC","NYC",[]),("Philadelphia Union","PHI",[]),("Portland Timbers","POR",[]),("Seattle Sounders","SEA",[]),("Real Salt Lake","RSL",[]),("Nashville SC","NSH",[]),("Austin FC","AUS",[]),("Charlotte FC","CLT",[]),("St. Louis City SC","STL",[]),("CF Montreal","MTL",[]),("Toronto FC","TOR",[]),("Vancouver Whitecaps","VAN",[]),("Houston Dynamo","HOU",[]),("FC Dallas","DAL",[]),("Minnesota United","MIN",[]),("Sporting Kansas City","SKC",[]),("Colorado Rapids","COL",[]),("San Jose Earthquakes","SJE",[]),("D.C. United","DCU",[]),("Chicago Fire","CHI",[]),("New England Revolution","NER",[]),("San Diego FC","SDG",[])])
add("Mexico","MX","Liga MX",[("Club America","AME",["Aguilas"]),("Guadalajara","GDL",["Chivas"]),("Cruz Azul","CAZ",[]),("UNAM Pumas","PUM",[]),("Tigres UANL","TIG",[]),("Monterrey","MTY",["Rayados"]),("Toluca","TOL",[]),("Santos Laguna","SAN",[]),("Leon","LEO",[]),("Pachuca","PAC",[]),("Atlas","ATL",[]),("Necaxa","NEC",[]),("Puebla","PUE",[]),("Queretaro","QRO",[]),("Mazatlan FC","MAZ",[]),("FC Juarez","JUA",[]),("Atletico San Luis","ASL",[]),("Tijuana","TIJ",["Xolos"])])
add("Canada","CA","Canadian Premier League",[("Forge FC","FOR",[]),("Cavalry FC","CAV",[]),("Pacific FC","PAC",[]),("Atletico Ottawa","OTT",[]),("Valour FC","VLR",[]),("York United FC","YRK",[]),("HFX Wanderers","HFX",[]),("Vancouver FC","VFC",[])])
add("Brazil","BR","Brasileirao Serie A",[("Flamengo","FLA",[]),("Palmeiras","PAL",[]),("Corinthians","COR",[]),("Sao Paulo","SAO",[]),("Fluminense","FLU",[]),("Gremio","GRE",[]),("Internacional","INT",[]),("Athletico Paranaense","CAP",[]),("Botafogo","BOT",[]),("Cruzeiro","CRU",[]),("Atletico Mineiro","CAM",[]),("Santos","SAN",[]),("Fortaleza","FOR",[]),("Bahia","BAH",[]),("Vasco da Gama","VAS",[]),("Vitoria","VIT",[]),("Juventude","JUV",[]),("Sport Recife","SPO",[]),("Bragantino","BRA",[]),("Cuiaba","CUI",[])])
add("Argentina","AR","Liga Profesional",[("River Plate","RIV",[]),("Boca Juniors","BOC",[]),("Racing Club","RAC",[]),("Independiente","IND",[]),("San Lorenzo","SLO",[]),("Velez Sarsfield","VEL",[]),("Estudiantes","EST",[]),("Talleres","TAL",[]),("Belgrano","BEL",[]),("Lanus","LAN",[]),("Banfield","BAN",[]),("Defensa y Justicia","DYJ",[]),("Godoy Cruz","GOD",[]),("Rosario Central","ROS",[]),("Newell's Old Boys","NOB",[]),("Colon","COL",[]),("Union de Santa Fe","UNI",[]),("Gimnasia y Esgrima LP","GEL",[]),("Platense","PLA",[]),("Tigre","TIG",[]),("Huracan","HUR",[]),("Instituto","INS",[]),("Sarmiento","SAR",[]),("Barracas Central","BAR",[]),("Riestra","RIE",[]),("Atletico Tucuman","ATU",[]),("Argentinos Juniors","ARJ",[]),("Central Cordoba","CCS",[])])
add("Colombia","CO","Categoria Primera A",[("Atletico Nacional","NAC",[]),("Millonarios","MIL",[]),("Junior","JUN",[]),("America de Cali","AME",[]),("Independiente Medellin","DIM",[]),("Deportivo Cali","CAL",[]),("Deportes Tolima","TOL",[]),("Santa Fe","SFE",[]),("Once Caldas","ONC",[]),("La Equidad","EQU",[]),("Deportivo Pasto","PAS",[]),("Envigado","ENV",[]),("Bucaramanga","BUC",[]),("Jaguares de Cordoba","JAG",[]),("Patriotas FC","PAT",[]),("Alianza FC","ALI",[])])
add("Chile","CL","Primera Division Chile",[("Colo-Colo","CCO",[]),("Universidad de Chile","UCH",[]),("Universidad Catolica","UCA",[]),("Union Espanola","UNE",[]),("Audax Italiano","AUI",[]),("Cobreloa","COB",[]),("Cobresal","COS",[]),("Everton Vina del Mar","EVE",[]),("Huachipato","HUA",[]),("O'Higgins","OHI",[]),("Palestino","PAL",[]),("Nublense","NUB",[]),("Coquimbo Unido","COQ",[]),("Deportes Iquique","DIQ",[]),("Santiago Wanderers","SAW",[])])
add("Peru","PE","Liga 1",[("Universitario","UNI",[]),("Alianza Lima","ALI",[]),("Sporting Cristal","SCR",[]),("Melgar","MEL",[]),("Cienciano","CIE",[]),("Sport Huancayo","SHU",[]),("Deportivo Municipal","MUN",[]),("Carlos Mannucci","CMA",[]),("Cesar Vallejo","CVA",[]),("ADT","ADT",[]),("UTC Cajamarca","UTC",[]),("Sport Boys","SPB",[])])
add("Ecuador","EC","Liga Pro",[("Barcelona SC","BSC",[]),("LDU Quito","LDU",[]),("Emelec","EME",[]),("Independiente del Valle","IDV",[]),("El Nacional","ELN",[]),("Deportivo Cuenca","CUE",[]),("Aucas","AUC",[]),("Delfin SC","DEL",[]),("Mushuc Runa","MRU",[]),("Tecnico Universitario","TUV",[])])
add("Uruguay","UY","Primera Division Uruguay",[("Nacional","NAC",[]),("Penarol","PEN",[]),("Danubio","DAN",[]),("Defensor Sporting","DEF",[]),("River Plate Montevideo","RPM",[]),("Liverpool Montevideo","LIV",[]),("Wanderers","WAN",[]),("Cerro","CER",[]),("Racing Montevideo","RAC",[]),("Progreso","PRO",[]),("Cerro Largo","CLG",[]),("Plaza Colonia","PLC",[]),("Boston River","BOS",[]),("Fenix","FEN",[])])
add("Paraguay","PY","Division de Honor",[("Olimpia","OLI",[]),("Cerro Porteno","CER",[]),("Libertad","LIB",[]),("Guarani","GUA",[]),("Nacional Asuncion","NAS",[]),("Sol de America","SOL",[]),("Sportivo Luqueno","SPL",[]),("12 de Octubre","DOC",[]),("Tacuary","TAC",[]),("Resistencia SC","RES",[])])
add("Bolivia","BO","Division Profesional",[("Bolivar","BOL",[]),("The Strongest","STR",[]),("Always Ready","ALR",[]),("Blooming","BLO",[]),("Oriente Petrolero","ORI",[]),("Wilstermann","WIL",[]),("Nacional Potosi","NAP",[]),("Royal Pari","RPA",[]),("Guabira","GUA2",[]),("Aurora","AUR",[])])
add("Venezuela","VE","Liga FUTVE",[("Caracas FC","CAR",[]),("Deportivo Tachira","TAC",[]),("Zamora FC","ZAM",[]),("Monagas SC","MON",[]),("Deportivo Lara","LAR",[]),("Mineros de Guayana","MIN",[]),("Metropolitanos FC","MET",[]),("Carabobo FC","CBO",[]),("Portuguesa FC","PRT",[]),("Estudiantes de Merida","EST",[])])
add("Costa Rica","CR","Liga FPD",[("Deportivo Saprissa","SAP",[]),("LD Alajuelense","LDA",[]),("CS Herediano","HER",[]),("CS Cartagines","CAR",[]),("AD Guanacasteca","GUA",[]),("Sporting FC","SFC",[]),("AD San Carlos","ASC",[]),("Santos de Guapiles","SDG",[]),("Puntarenas FC","PUN",[]),("Municipal Grecia","GRE",[])])
add("Panama","PA","Liga Panamena",[("Tauro FC","TAU",[]),("Plaza Amador","PLA",[]),("Arabe Unido","ARU",[]),("CAI de La Chorrera","CAI",[]),("CD Universitario","UNI",[]),("Sporting SM","SSM",[]),("San Francisco FC","SFF",[]),("Herrera FC","HFC",[])])
add("Honduras","HN","Liga Nacional Honduras",[("Olimpia Honduras","OLI",[]),("Motagua","MOT",[]),("Real Espana","RES",[]),("Marathon","MAR",[]),("Platense Honduras","PLA",[]),("Victoria","VIC",[]),("UPNFM","UPN",[]),("Honduras Progreso","HOP",[]),("Vida","VID",[]),("Genesis","GEN",[])])
add("El Salvador","SV","Primera Division SV",[("CD FAS","FAS",[]),("Alianza FC SV","ALI",[]),("CD Aguila","AGU",[]),("Once Deportivo","OND",[]),("Santa Tecla FC","STE",[]),("Isidro Metapan","MET",[]),("Municipal Limeno","MUL",[]),("Jocoro FC","JOC",[]),("CD Luis Angel Firpo","FIR",[])])
add("Guatemala","GT","Liga Nacional Guatemala",[("Municipal Guatemala","MUN",[]),("Comunicaciones","COM",[]),("Antigua GFC","ANT",[]),("Guastatoya","GUA",[]),("Coban Imperial","COB",[]),("Xelaju MC","XEL",[]),("Malacateco","MAL",[]),("Mixco","MIX",[]),("Deportivo Iztapa","IZT",[])])
add("Jamaica","JM","Jamaica Premier League",[("Arnett Gardens","ARN",[]),("Harbour View","HRB",[]),("Waterhouse FC","WAT",[]),("Cavalier FC","CAV",[]),("Mount Pleasant FA","MTP",[]),("Tivoli Gardens","TIV",[]),("Portmore United","PMU",[]),("Humble Lion","HUM",[]),("Dunbeholden FC","DUN",[])])
add("Trinidad and Tobago","TT","TT Pro League",[("Defence Force","DEF",[]),("AC Port of Spain","ACP",[]),("W Connection","WCO",[]),("Central FC","CFI",[]),("Club Sando","CSA",[]),("Morvant Caledonia","MOR",[]),("Police FC TT","PFC",[])])
add("Dominican Republic","DO","Liga Dominicana",[("Cibao FC","CIB",[]),("Atletico Pantoja","ATP",[]),("Moca FC","MOC",[]),("Universidad OM","OM",[]),("Atletico San Francisco","ASF",[]),("Delfines del Este","DDE",[])])
add("Haiti","HT","Ligue Haitienne",[("Racing Club Haitien","RCH",[]),("Violette AC","VIO",[]),("Aigle Noir","AIG",[]),("Don Bosco FC","DBF",[]),("AS Capoise","ASC",[]),("Arcahaie FC","ARC",[]),("Cavaly AS","CAV",[])])
add("Cuba","CU","Campeonato Nacional Cuba",[("FC Villa Clara","VCL",[]),("FC Pinar del Rio","PDR",[]),("FC Santiago de Cuba","SDC",[]),("FC Camaguey","CAM",[]),("FC Holguin","HOL",[]),("FC La Habana","HAB",[])])
add("Nicaragua","NI","Liga Primera Nicaragua",[("Real Esteli","RES",[]),("CD Managua","MAN",[]),("Diriangen FC","DIR",[]),("UNAN Managua","UNA",[]),("Walter Ferretti","WFE",[]),("CD Ocotal","OCO",[])])

# Remove empty entries
L = {k: v for k, v in L.items() if len(v) > 0}

# Generate output
sql_lines = ["BEGIN;", ""]
json_teams = []
total = 0

for (country, cc, league), tlist in L.items():
    sql_lines.append(f"-- {country} ({cc}) - {league} ({len(tlist)} teams)")
    for (name, short, aliases) in tlist:
        tid = slugify(name, cc)
        search = list(set(aliases + [short]))
        search_pg = '{' + ','.join(f'"{a}"' for a in search) + '}'
        sql_lines.append(
            f"INSERT INTO public.teams (id, name, short_name, country, country_code, league_name, search_terms, is_active, updated_at) "
            f"VALUES ('{tid}', '{esc(name)}', '{short}', '{esc(country)}', '{cc}', '{esc(league)}', '{search_pg}', true, now()) "
            f"ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, short_name=EXCLUDED.short_name, country=EXCLUDED.country, "
            f"country_code=EXCLUDED.country_code, league_name=EXCLUDED.league_name, search_terms=EXCLUDED.search_terms, "
            f"is_active=true, updated_at=now();"
        )
        json_teams.append({
            "id": tid, "name": name, "short_name": short,
            "country": country, "country_code": cc, "league_name": league,
            "search_terms": search, "crest_url": None, "is_active": True,
        })
        total += 1
    sql_lines.append("")

sql_lines.append("COMMIT;")
sql_lines.append(f"-- Total teams seeded: {total}")

sql_path = "/Volumes/PRO-G40/FANZONE/supabase/migrations/20260420090000_seed_global_teams.sql"
with open(sql_path, 'w') as f:
    f.write('\n'.join(sql_lines))
print(f"SQL: {sql_path} ({total} teams)")

json_path = "/Volumes/PRO-G40/FANZONE/assets/data/team_search_database.json"
with open(json_path, 'w') as f:
    json.dump({"teams": json_teams, "count": total}, f, indent=2, ensure_ascii=False)
print(f"JSON: {json_path} ({total} teams)")

countries = set(cc for (_, cc, _) in L.keys())
print(f"\nSummary: {len(countries)} countries, {len(L)} leagues, {total} teams")
