import { Link } from "react-router-dom";
import { ChevronLeft } from "lucide-react";

type LegalPageKind = "privacy" | "terms" | "fet" | "help";

const legalContent: Record<
  LegalPageKind,
  {
    eyebrow: string;
    title: string;
    updated: string;
    sections: Array<{ title: string; body: string[] }>;
  }
> = {
  privacy: {
    eyebrow: "Privacy",
    title: "FANZONE Privacy Policy",
    updated: "May 3, 2026",
    sections: [
      {
        title: "Information we collect",
        body: [
          "FANZONE collects WhatsApp phone number for OTP login, an autogenerated 6-digit FANZONE ID, fan profile preferences, venue interactions, order records, manual payment status, wallet ledger activity, pools, games, teams, invites, and support activity.",
          "If notifications are enabled, FANZONE stores Firebase Cloud Messaging tokens. Runtime diagnostics may be logged to operate and improve the service.",
        ],
      },
      {
        title: "Payments",
        body: [
          "FANZONE does not process payment cards, bank accounts, MoMo credentials, or Revolut credentials in the MVP release. Venues provide external payment instructions and manually confirm paid orders.",
        ],
      },
      {
        title: "How we use data",
        body: [
          "We use data to authenticate users, operate venue ordering, manage FET wallets and ledgers, settle pools and games, enforce eligibility rules, provide support, prevent abuse, and maintain platform security.",
        ],
      },
      {
        title: "Sharing",
        body: [
          "Venue staff can see venue-linked operational data needed to manage orders, games, pools, teams, and payment confirmation. FANZONE does not sell personal data.",
        ],
      },
      {
        title: "Retention and deletion",
        body: [
          "Users may request account deletion through the app or by contacting info@ikanisa.com. Some order, wallet, ledger, audit, and settlement records may be retained when required for integrity, disputes, fraud prevention, and legal compliance.",
        ],
      },
    ],
  },
  terms: {
    eyebrow: "Terms",
    title: "FANZONE Terms of Use",
    updated: "May 3, 2026",
    sections: [
      {
        title: "Service",
        body: [
          "FANZONE provides sports-bar venue discovery, dine-in ordering support, external payment guidance, closed-loop FET reward points, prediction pools, centralized entertainment games, teams, and venue TV screen experiences.",
        ],
      },
      {
        title: "Accounts",
        body: [
          "Users sign in with WhatsApp OTP. FANZONE does not require names, usernames, or email addresses. Each user receives an autogenerated 6-digit FANZONE ID.",
        ],
      },
      {
        title: "Orders and payments",
        body: [
          "Orders are linked to venues. Payment is external and handled by the venue through MoMo USSD, Revolut link, cash, or other venue instructions. FANZONE does not process external payment credentials in the MVP release.",
        ],
      },
      {
        title: "Pools and games",
        body: [
          "Prediction pools and games use FET points only and are linked to venues. FANZONE may restrict, cancel, settle, reverse, or audit pools and games to enforce eligibility, integrity, and platform rules.",
        ],
      },
      {
        title: "Contact",
        body: [
          "Contact info@ikanisa.com for support, disputes, or account requests.",
        ],
      },
    ],
  },
  fet: {
    eyebrow: "FET Rewards",
    title: "FET Reward Terms",
    updated: "May 3, 2026",
    sections: [
      {
        title: "Closed-loop points",
        body: [
          "FET is a closed-loop engagement and reward point used inside FANZONE and participating venue experiences. FET is not cash, not cryptocurrency trading, not a financial instrument, not an investment product, and not withdrawable.",
        ],
      },
      {
        title: "Eligibility",
        body: [
          "To receive FET winnings from a linked game or prediction pool, a user must place at least one qualifying paid order from the linked venue within 2 hours before the scheduled game or pool start time.",
          "Users may join before ordering. Ineligible winners may still appear as winners but do not receive FET settlement.",
        ],
      },
      {
        title: "Ledger",
        body: [
          "Every FET movement must be recorded in the ledger. Wallet balances must not be changed without a ledger entry, and wallets must not go negative.",
        ],
      },
    ],
  },
  help: {
    eyebrow: "Support",
    title: "FANZONE Help",
    updated: "May 3, 2026",
    sections: [
      {
        title: "Contact support",
        body: [
          "Email info@ikanisa.com for account, order, venue, wallet, pool, game, or TV screen support.",
        ],
      },
      {
        title: "Order disputes",
        body: [
          "Food and drink payment is handled externally by the venue. If payment status looks wrong, contact venue staff first and include your 6-digit FANZONE ID and order number when contacting FANZONE support.",
        ],
      },
      {
        title: "Account deletion",
        body: [
          "You can request account deletion from the app where available or by emailing info@ikanisa.com from the WhatsApp number linked to your FANZONE account.",
        ],
      },
    ],
  },
};

export default function LegalPage({ kind }: { kind: LegalPageKind }) {
  const content = legalContent[kind];

  return (
    <main className="min-h-screen bg-bg px-5 py-8 text-text">
      <div className="mx-auto max-w-3xl">
        <Link
          to="/"
          className="inline-flex items-center gap-2 rounded-full border border-border bg-surface2 px-4 py-2 text-sm font-bold text-muted transition hover:text-text"
        >
          <ChevronLeft size={16} />
          Back to FANZONE
        </Link>
        <p className="mt-10 text-xs font-black uppercase tracking-[0.28em] text-accent">
          {content.eyebrow}
        </p>
        <h1 className="mt-3 font-display text-4xl font-black tracking-tight text-text md:text-5xl">
          {content.title}
        </h1>
        <p className="mt-3 text-sm font-bold text-muted">
          Last updated: {content.updated}
        </p>

        <div className="mt-10 space-y-5">
          {content.sections.map((section) => (
            <section
              key={section.title}
              className="rounded-[28px] border border-border bg-surface2 p-6"
            >
              <h2 className="font-display text-2xl font-black text-text">
                {section.title}
              </h2>
              <div className="mt-4 space-y-4 text-base font-semibold leading-7 text-muted">
                {section.body.map((paragraph) => (
                  <p key={paragraph}>{paragraph}</p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}
